[package]
name = "bingrep"
version = "0.1.0"
authors = ["Mark Barbone <mark.l.barbone@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
memmap = "0.7"
indicatif = "0.14"
structopt = "0.3"
